"""
Markdown wiki writer. One page per tracked entity (company/facility/operator
or case), plus an auto-generated index sorted by composite priority score
(highest = most severe/well-documented/urgent first).

Pages are fully regenerated from the store on each write (idempotent), so the
wiki is always a clean projection of the SQLite state -- no drift. Writes
land in the agent's `wiki_dir`, which agent_spark_core.wiki_git then
commits and pushes to the agent's shared GitHub repo.
"""

import time
from datetime import datetime, timezone

from slugify import slugify

from agent_def import config

DIMENSION_LABELS = {
    "evidence_strength": "Evidence Strength",
    "severity": "Severity",
    "legal_exposure": "Legal Exposure",
    "recency": "Recency",
}


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _bar(score: float) -> str:
    """0..5 filled bar, e.g. [###-------] used for each dimension."""
    span = config.SCORE_MAX - config.SCORE_MIN
    filled = round((score - config.SCORE_MIN) / span * 20) if span else 0
    filled = max(0, min(20, filled))
    return "[" + ("#" * filled) + ("-" * (20 - filled)) + f"] {score:.1f}/5"


def _pool_for_entity(store, entity: str) -> str:
    facts = store.facts_for_entity(entity)
    return facts[0]["pool"] if facts else "unknown"


def write_entity_page(store, cfg, entity: str):
    facts = store.facts_for_entity(entity)
    scores = {s["dimension"]: s for s in store.scores_for_entity(entity)}
    pool = _pool_for_entity(store, entity)
    kind = "Case" if pool == "case_law" else "Entity"

    slug = slugify(entity)
    subdir = "cases" if pool == "case_law" else "entities"
    path = cfg.wiki_dir / subdir / f"{slug}.md"
    path.parent.mkdir(parents=True, exist_ok=True)

    lines = [f"# {entity}", "", f"_{kind} · pool: `{pool}` · last updated: {_now()}_", ""]

    if scores:
        composite = sum(s["score"] for s in scores.values()) / len(scores)
        lines += ["## Priority Summary", "", f"**Composite priority: {composite:.1f}/5**", ""]
        lines.append("| Dimension | Score |")
        lines.append("|---|---|")
        for dim in config.SCORING_DIMENSIONS:
            s = scores.get(dim)
            if not s:
                continue
            lines.append(f"| {DIMENSION_LABELS[dim]} | `{_bar(s['score'])}` |")
        lines.append("")

        lines.append("## Rationale by Dimension")
        lines.append("")
        for dim in config.SCORING_DIMENSIONS:
            s = scores.get(dim)
            if not s:
                continue
            lines.append(f"### {DIMENSION_LABELS[dim]} ({s['score']:.1f}/5)")
            lines.append("")
            lines.append(s["rationale"] or "_no rationale recorded_")
            lines.append("")
    else:
        lines += ["## Priority Summary", "", "_Not yet scored -- insufficient facts gathered._", ""]

    lines.append("## Supporting Facts")
    lines.append("")
    if facts:
        for f in facts:
            dim_label = DIMENSION_LABELS.get(f["dimension"], "unclassified")
            lines.append(f"- **[{dim_label}]** {f['fact']}  ")
            lines.append(f"  _source: <{f['source_url']}>_")
    else:
        lines.append("_No facts gathered yet._")
    lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def write_index(store, cfg):
    entities = store.all_entities()
    rows = []
    for entity in entities:
        scores = store.scores_for_entity(entity)
        if not scores:
            continue
        composite = sum(s["score"] for s in scores) / len(scores)
        pool = _pool_for_entity(store, entity)
        rows.append((entity, composite, len(scores), pool))

    rows.sort(key=lambda r: r[1], reverse=True)  # most severe/documented first

    lines = [
        "# Animal Rights Watch Wiki",
        "",
        f"_Last updated: {_now()}_",
        "",
        "Auto-generated by the animal-rights-watch agent. Tracks two kinds of entities: companies/"
        "facilities/operators implicated in systemic animal-rights violations, and animal-cruelty / "
        "animal-rights case law across all 50 US states. Each is scored 0-5 on four dimensions: "
        "evidence strength, severity, legal exposure, and recency.",
        "",
        "## Tracked Entities Ranked by Composite Priority (highest first)",
        "",
        "| Entity / Case | Pool | Composite | Dimensions Scored | Page |",
        "|---|---|---|---|---|",
    ]
    for entity, composite, n_dims, pool in rows:
        slug = slugify(entity)
        subdir = "cases" if pool == "case_law" else "entities"
        lines.append(f"| {entity} | {pool} | {composite:.1f}/5 | {n_dims}/4 | [view]({subdir}/{slug}.md) |")

    if not rows:
        lines.append("| _(none scored yet)_ | | | | |")

    stats = store.stats()
    lines += [
        "",
        "## Crawl Stats",
        "",
        f"- Pages fetched: {stats['done']}",
        f"- Pages pending: {stats['pending']}",
        f"- Pages failed: {stats['failed']}",
        f"- Entities tracked: {stats['entities']}",
        f"- Facts extracted: {stats['facts']}",
        "",
    ]

    path = cfg.wiki_dir / "index.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def rebuild_all(store, cfg):
    t0 = time.time()
    entities = store.all_entities()
    for entity in entities:
        write_entity_page(store, cfg, entity)
    write_index(store, cfg)
    import logging

    logging.getLogger("animal_rights_watch.wiki").info(
        "wiki rebuilt (%d entities) in %.1fs", len(entities), time.time() - t0
    )
