"""
Markdown wiki writer. One page per HCPCS code / drug, plus an auto-generated
index sorted by how net-favorable the code currently looks for Cigna vs Mt
Sinai.

Pages are fully regenerated from the store on each write (idempotent), so the
wiki is always a clean projection of the SQLite state -- no drift. Writes land
in the instance's `wiki_dir`, which agent_spark_core.wiki_git then commits and
pushes to the agent's shared GitHub repo.

Direct port of leverage-agent/agent/wiki.py.
"""

import time
from datetime import datetime, timezone

from slugify import slugify

from agent_def import config

DIMENSION_LABELS = {
    "market_network": "Market / Network Position",
    "financial": "Financial Condition",
    "regulatory_pricing": "Regulatory & Pricing Benchmarks",
    "clinical_uniqueness": "Clinical Uniqueness",
}


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _bar(score: float) -> str:
    """Render a simple text leverage bar, e.g. Cigna <====|====> Mt Sinai"""
    pos = round((score - config.SCORE_MIN) / (config.SCORE_MAX - config.SCORE_MIN) * 20)
    pos = max(0, min(20, pos))
    return "Cigna " + ("─" * pos) + "●" + ("─" * (20 - pos)) + " Mt Sinai"


def write_entity_page(store, cfg, entity: str):
    facts = store.facts_for_entity(entity)
    scores = {s["dimension"]: s for s in store.scores_for_entity(entity)}

    slug = slugify(entity)
    path = cfg.wiki_dir / "codes" / f"{slug}.md"
    path.parent.mkdir(parents=True, exist_ok=True)

    lines = [f"# {entity}", "", f"_Last updated: {_now()}_", ""]

    if scores:
        net = sum(s["score"] for s in scores.values()) / len(scores)
        lines += [
            "## Leverage Summary", "",
            f"**Net leverage: {net:+.1f}** (negative = favors Cigna, positive = favors Mt Sinai)", "",
        ]
        lines.append("| Dimension | Score | Leverage |")
        lines.append("|---|---|---|")
        for dim in config.LEVERAGE_DIMENSIONS:
            s = scores.get(dim)
            if not s:
                continue
            lines.append(f"| {DIMENSION_LABELS[dim]} | {s['score']:+.1f} | `{_bar(s['score'])}` |")
        lines.append("")

        lines.append("## Rationale by Dimension")
        lines.append("")
        for dim in config.LEVERAGE_DIMENSIONS:
            s = scores.get(dim)
            if not s:
                continue
            lines.append(f"### {DIMENSION_LABELS[dim]} ({s['score']:+.1f})")
            lines.append("")
            lines.append(s["rationale"] or "_no rationale recorded_")
            lines.append("")
    else:
        lines += ["## Leverage Summary", "", "_Not yet scored -- insufficient facts gathered._", ""]

    lines.append("## Supporting Facts")
    lines.append("")
    if facts:
        for f in facts:
            dim_label = DIMENSION_LABELS.get(f["dimension"], "unclassified")
            lines.append(f"- **[{dim_label}]** {f['fact']}  ")
            lines.append(f"  _source: <{f['source_url']}>_")
    else:
        lines.append("_No facts gathered yet._")
    lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def write_index(store, cfg):
    entities = store.all_entities()
    rows = []
    for entity in entities:
        scores = store.scores_for_entity(entity)
        if not scores:
            continue
        net = sum(s["score"] for s in scores) / len(scores)
        rows.append((entity, net, len(scores)))

    rows.sort(key=lambda r: r[1])  # most Cigna-favorable first

    lines = [
        "# Cigna ↔ Mt Sinai Contract Leverage Wiki",
        "",
        f"_Last updated: {_now()}_",
        "",
        "Auto-generated by the cigna-mtsinai-negotiation agent. Each page tracks negotiating leverage "
        "for a specific HCPCS/CPT code or drug across four dimensions: market/network position, "
        "financial condition, regulatory & pricing benchmarks, and clinical uniqueness.",
        "",
        "Score scale: **-5 = strongly favors Cigna** ... **0 = neutral** ... **+5 = strongly favors Mt Sinai**.",
        "",
        "## Codes Ranked by Net Leverage (most Cigna-favorable first)",
        "",
        "| Code | Net Leverage | Dimensions Scored | Page |",
        "|---|---|---|---|",
    ]
    for entity, net, n_dims in rows:
        slug = slugify(entity)
        lines.append(f"| {entity} | {net:+.1f} | {n_dims}/4 | [view](codes/{slug}.md) |")

    if not rows:
        lines.append("| _(none scored yet)_ | | | |")

    stats = store.stats()
    lines += [
        "",
        "## Crawl Stats",
        "",
        f"- Pages fetched: {stats['done']}",
        f"- Pages pending: {stats['pending']}",
        f"- Pages failed: {stats['failed']}",
        f"- Codes tracked: {stats['entities']}",
        f"- Facts extracted: {stats['facts']}",
        "",
    ]

    path = cfg.wiki_dir / "index.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def rebuild_all(store, cfg):
    """Regenerate every entity page + index from current DB state."""
    t0 = time.time()
    entities = store.all_entities()
    for entity in entities:
        write_entity_page(store, cfg, entity)
    write_index(store, cfg)
    import logging

    logging.getLogger("cigna_mtsinai.wiki").info(
        "wiki rebuilt (%d codes) in %.1fs", len(entities), time.time() - t0
    )
